### ISSUE TITLE
test run

### ISSUE THREAD

**Issue by clemdawg** [f-heeger/two_marker_metabarcoding#5]
Hello Felix,

After the installation I tried:
snakemake --use-conda -s metabarcoding.snakemake.py -j 2

I get the following error message 
Building DAG of jobs...
Creating conda environment envs/multiqc.yaml...
Downloading and installing remote packages.
Environment for envs/multiqc.yaml created (location: .snakemake/conda/2a0756b32b9f6d2e127d146793de8ded)
Creating conda environment envs/vsearch.yaml...
Downloading and installing remote packages.
Environment for envs/vsearch.yaml created (location: .snakemake/conda/742f1cbd61c45fbba553b1c74ecedf32)
Creating conda environment envs/lambda.yaml...
Downloading and installing remote packages.
CreateCondaEnvironmentException:
Could not create conda environment from /Users/home/fungi_pipe/two_marker_metabarcoding-master/envs/lambda.yaml:
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed

ResolvePackageNotFound:
  - lambda=2.0.0

File "/Users/home/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/deployment/conda.py", line 387, in create

Any idea how I can resolve this?

**Comment by f-heeger** [comment]
This is most likely an issue with the lambda2 conda distribution not containing executables for MacOS. This could only be fixed by the maintainers of that package including them.

A possible workaround might be to install lambda manually and change the rules that use it to not use conda (or run those rules on their own without the use-conda flag).

**Comment by clemdawg** [comment]
Hi Felix,

sorry for not responding earlier.

Alice helped me fix the problem with the lamba2 installation.

The pipeline seems to work now.

Have a nice weekend.

Clemens
